version: '3.9'

services:
  db:
    image: postgres:13
    container_name: solemate_db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: new
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: akkufauzu
    networks:
      - solemate_network

  app:
    build: .
    command: python manage.py migrate
    container_name: solemate_app_container
    volumes:
      - .:/app
    depends_on:
      - db
    environment:
      - DB_NAME=new
      - DB_USER=postgres
      - DB_PASSWORD=akkufauzu
      - DB_HOST=db
      - DB_PORT=5432
    networks:
      - solemate_network

networks:
  solemate_network:  

volumes:
  postgres_data:
