version: '3.9'

services:
  db:
    image: postgres:13
    container_name: solemate_db_container
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${NAME}
      POSTGRES_USER: ${USR}
      POSTGRES_PASSWORD: ${PASSWORD}

  app:
    build: .
    container_name: solemate_app_container
    volumes:
      - .:/app
      - ./static:/app/static
      - ./media:/app/media
    depends_on:
      - db
    environment:
      - DB_NAME=${NAME}
      - DB_USER=${USR}
      - DB_PASSWORD=${PASSWORD}
      - DB_HOST=${HOST}
      - DB_PORT=${PORT}



networks:
  solemate_network:   

volumes:
  postgres_data:
