apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: new
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: akkufauzu
          volumeMounts:
            - name: postgres-pvc
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: postgres-pvc
          persistentVolumeClaim:
            claimName: postgres-pvc
      # The issue may be because you should do this in the django container
      # initContainers:
      #   - name: migration
      #     image: fauzu/solemat:latest
      #     command: ["python", "manage.py", "migrate"]
      #     env:
      #       - name: DB_HOST
      #         value: db
      #       - name: DB_PORT
      #         value: "5432"
      #       - name: DB_NAME
      #         value: solemate_db
      #       - name: DB_USER
      #         value: postgres
      #       - name: DB_PASSWORD
      #         value: akkufauzu

---

apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port: 5432
